### ISSUE TITLE
where to put the 100% save file in?

### ISSUE THREAD

**Issue by Supergub5871** [Llennpie/Saturn#11]
idk where the saves for Saturn go's to help pls

**Comment by Llennpie** [comment]
Check the [File Guide](https://github.com/Llennpie/Saturn/wiki/File-Guide). The wiki has all the answers, please refer to there before creating an issue.

**Comment by Supergub5871** [comment]
SATURNME FOLDER IS FOR SATURN MOON ONLY BRUH

**Comment by Supergub5871** [comment]
THE The wiki has all the answers, THING IS A LIE

**Comment by Supergub5871** [comment]
AND YEP NO SAVE .BIN THING ANYWHERE DUMB HEAD

**Comment by Supergub5871** [comment]
sorry i was dumb

**Comment by Supergub5871** [comment]
its in appdata
