### ISSUE TITLE
A few option ideas idk (I have no idea how to add labels so sorry for that)

### ISSUE THREAD

**Issue by OvercastGM** [Llennpie/Saturn#13]
Possibly an option to hold animations at the end like M64MM3?

also idk if this was recommended but maybe custom map support (mostly for huge town/glowshire)

**Comment by Llennpie** [comment]
It's already possible to select specific animation frames (including the end) with Saturn's animation player. Custom map support is not planned or on the to-do at this time, but I will look into the possibility at some point.
