### ISSUE TITLE
Having.... this issue

### ISSUE THREAD

**Issue by PaperVb64** [Llennpie/Saturn#14]
![Screenshot 2022-04-27 2 36 35 PM](https://user-images.githubusercontent.com/94991205/165596338-ffbc3975-dc87-4bea-88c0-565c4d2693d2.png)
it's just completely blank with sound.

**Comment by Llennpie** [comment]
Is this `legacy` or `moon`? Also can you list some PC specs? This screenshot alone isn't telling much.

**Comment by PaperVb64** [comment]
Legacy. Also, i'm that guy that kept trying to run it on chrome os via the linux terminal. The executable exists, but it just shows a blank screen and sounds.

**Comment by PaperVb64** [comment]
the sounds play, but something's obscuring the view, ailbet

**Comment by PaperVb64** [comment]
sry closing this cuz my first issue on buster helped a lot.
