### ISSUE TITLE
The addons site doesn't work, is there another place I can get the moon64 default addon?

### ISSUE THREAD

**Issue by OvercastGM12** [Llennpie/Saturn#15]

**Comment by OvercastGM12** [comment]
I had to factory reset my PC and can't redownload it

**Comment by Llennpie** [comment]
Unfortunately the Moon64 site is down, and we're waiting on the developer (KiritoDev) to bring it back up. No ETA I'm afraid

In the meantime I recommend just compiling the legacy branch, it's updated often and has far more features. It's in sm64pcBuilder2
