### ISSUE TITLE
Saturn will not compile on KDE Neon

### ISSUE THREAD

**Issue by SlideVRalt** [Llennpie/Saturn#22]
When you makefile on the folder itself, it will compile for a minute then it will show this;
(NOTE: THE SAME THING HAPPENS ON EX-COOP AS WELL, SO I PUT A SCREENSHOT OF SM64EX-COOP COMPILING.)
![image](https://user-images.githubusercontent.com/106561594/218321989-abdf8243-c040-461e-b8ef-9a61645302c2.png)

**Comment by SlideVRalt** [comment]
the reason why i put a picture of ex-coop compiling is because i didnt want to take the time to screenshot saturn compiling

**Comment by Llennpie** [comment]
Looks like you are missing dependencies, specifically SDL2. KDE Neon is based on Ubuntu so refer to [Compiling on Linux](https://github.com/Llennpie/Saturn/wiki/Compiling-on-Linux) as an install guide.

**Comment by SlideVRalt** [comment]
> Looks like you are missing dependencies, specifically SDL2. KDE Neon is based on Ubuntu so refer to [Compiling on Linux](https://github.com/Llennpie/Saturn/wiki/Compiling-on-Linux) as an install guide.

I did the same thing I did on Ubuntu. Let me try installing dependencies like you said.

**Comment by Llennpie** [comment]
Closing this from inactivity, I assume the error been resolved? Feel free to reopen if you're still having this issue.

**Comment by SlideVRalt** [comment]
Funny thing; it does the same thing on Chromebook (using a Debian subsystem.)
_**Possible Saturn Chromebook support?**_

**Comment by SlideVRalt** [comment]
CORRECTION: linux subsystem (i mix words up)

**Comment by integerbang** [comment]
> Funny thing; it does the same thing on Chromebook (using a Debian subsystem.)

Linux on ChromeOS requires the same [build dependencies](https://github.com/sm64pc/sm64ex/wiki/Compiling-on-Linux#debian--ubuntu---targeting-64-bits) as any regular Debian installation.

However, you may need to search the [Debian Package archive](https://packages.debian.org/index) for dependencies exclusive to Saturn (e.g., [JsonCpp](https://github.com/open-source-parsers/jsoncpp)).

**Comment by integerbang** [comment]
Okay, I double-checked, and it seems all of the package names listed on the "[Compiling on Linux](https://github.com/Llennpie/Saturn/wiki/Compiling-on-Linux)" page are, in fact, applicable to Debian.

Correct me if I'm wrong, though.

**Comment by SlideVRalt** [comment]
> Okay, I double-checked, and it seems all of the package names listed on the "[Compiling on Linux](https://github.com/Llennpie/Saturn/wiki/Compiling-on-Linux)" page are, in fact, applicable to Debian.
> 
> Correct me if I'm wrong, though.

Yes, indeed. That means.... **saturn chromebook support.........** it's possible
