### ISSUE TITLE
Add Custom Map Support

### ISSUE THREAD

**Issue by Supergub5871** [Llennpie/Saturn#27]
Add So You Can Add A 3d Model (AKA .obj Files) And The Game Will Play The Map Without Deleting Other Maps (If Possible And i Have No Coding experience)

**Comment by KrazyGyro9704** [comment]
> Add So You Can Add A 3d Model (AKA .obj Files) And The Game Will Play The Map Without Deleting Other Maps (If Possible And i Have No Coding experience)

There's more to a map model than that. It would probably have to do with Fast64's level exporter and formatting all of the textures to work in Saturn (similar to GMM64's map pack). Not to mention the file editing that Fast64 instructs you to do to even get the map to be processed by the compiler in the first place.

**Comment by Supergub5871** [comment]
ok

**Comment by Llennpie** [comment]
> Add So You Can Add A 3d Model (AKA .obj Files) And The Game Will Play The Map Without Deleting Other Maps (If Possible And i Have No Coding experience)

This will not be worked on. Additionally, if a custom level system was considered, it would use the standard Fast64/decomp C structure, not OBJ or other model formats.
