### ISSUE TITLE
Black Display

### ISSUE THREAD

**Issue by Kaiju2019** [Llennpie/Saturn#29]
For some reason, after I compiled Saturn and ran the command to open it, it...had a black screen. No, Saturn does not crash, and no, I didn't forget to try freezing and unfreezing the camera. I would like support on this, please.

NOTE: I have a **Chromebook** with Linux on it, HOWEVER, there are no distorted sounds. It sounds perfectly smooth. I also don't know about the "Curl" thing either.

**Comment by integerbang** [comment]
Saturn isn't officially supported under Linux on ChromeOS, nor is there a way to run it without support for OpenGL 2.1 or later on the container's side.

**Comment by Kaiju2019** [comment]
well then why didnt it say when i opened it "OpenGL 2.1 or higher required" like sm64ex-coop does when i use anti aliasing, and then i have to delete the entire sm64config file?

**Comment by integerbang** [comment]
> well then why didnt it say when i opened it "OpenGL 2.1 or higher required" like sm64ex-coop does when i use anti aliasing

Your environment is reporting the right version of OpenGL, but whatever's supported likely has problems.

Just to clarify, Linux on ChromeOS _does_ support [accelerated graphics via OpenGL](https://chromeos.dev/en/linux/linux-on-chromeos-deep-dive#runtime-features), but it isn't perfect nor is it always up-to-date based on what I've been able to look up.

If you could, [try getting information using `glxinfo`](https://wiki.debian.org/Mesa#Get_informations_from_Mesa) and, optionally, [run a benchmark afterward](https://wiki.debian.org/Mesa#Testing_performance) to ensure everything works properly.

> and then i have to delete the entire sm64config file?

I'm unsure what you mean by this.

**Comment by integerbang** [comment]
Either way, @Kaiju2019, it's a problem with your environment if games don't display properly or claim there's no OpenGL support during startup. It isn't something one can provide direct support for, especially since neither the developer nor any of the contributors have a ChromeOS device to debug Saturn with.

**Comment by Kaiju2019** [comment]
Okay. Thank you for your support. I will try to use what you have informed me about, and see what comes. Also, I meant in sm64ex-coop, there is a configuration file I deleted because I activated a setting and it said Restart to use and I did and it said that openGL 2.1+ is required. Anyway, thank you again for your support.
