### ISSUE TITLE
My PC is Saturnproof

### ISSUE THREAD

**Issue by EP7O** [Llennpie/Saturn#37]
**Describe the bug**
I had just downloaded the Custom Maps version yesterday and when I mapped the buttons, It crashed and this affected my original version of legacy and no matter how much I try deleting and reinstalling, it always crashes.

**To Reproduce**
1. Go to 'Saturn Custom Maps'
2. Click on 'Mario's House Exterior'
3. Map the camera buttons
4. your done for

**Expected behavior**
I was just exploring the custom maps.

**Screenshots**
![image](https://github.com/Llennpie/Saturn/assets/143665154/c0926f49-5fc9-40b1-80eb-657c73e9e1d9)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Opera GX
 - Version 10.0.22621

**Comment by Dominicentek** [comment]
by the wording it seems like saturn worked before, maybe it has something to do with the settings
try deleting sm64config.txt to reset your settings,
its located in %appdata%\v64saturn\

**Comment by EP7O** [comment]
It didn't work...

**Comment by EP7O** [comment]
I tried deleting reinstalling PC Builder and reinstalling and it still didn't work.

**Comment by Llennpie** [comment]
The custom maps fork is not officially supported (nor is this even the right place). I recommend [submitting a PR to its repo](https://github.com/GlitchyMarioMario64/Saturn-Custom-Maps/pulls) instead so the developer can debug the problem.
