### ISSUE TITLE
Linux terminal won't allow me to run Saturn's main file

### ISSUE THREAD

**Issue by PaperVb64** [Llennpie/Saturn#4]
**_OH BOY HERE HE GOES AGAIN WITH A CHROME OS ISSUE-_**
In all seriousness though, i didn't have any issues installing! sure, i DID have a bit of trouble getting 7-zip, but i worked it out in the end.  LAST time i opened an issue, it was about installing. this time it's about USING Saturn.

Version: Saturn: Moon Edition
OS: Chrome OS (64 Bit)
Linux Terminal Version: Debian Buster

Soo, the file's there this time (oh thank GOD), but this shows up when trying to open it:
`~$ cd Saturn_ME
~/Saturn_ME$ ./saturn.us.f3dex2e 
-bash: ./saturn.us.f3dex2e: Permission denied `
Please note that i'm on my own account, and this is my linux profile that i'm using.

**Comment by PaperVb64** [comment]
It fixed the file error, but it says something about "GLIBC_2.29" not being found. What's that?

**Comment by PaperVb64** [comment]
It also says something about "GBLICXX_3.4.26" not being found.

**Comment by Llennpie** [comment]
You seem to be missing (or have an older version of) libc6 and/or libstdc++6.
```
sudo apt-get update
sudo apt-get install libc6 libstdc++6
```

**Comment by PaperVb64** [comment]
says it's in the latest version. I'll try running it again

**Comment by PaperVb64** [comment]
tried again. says something about GLBIC and GLBICXX. I keep having that issue, not libstdc

**Comment by Llennpie** [comment]
Can you try running these two commands for me, and sending back the entire output?

*This command will find out the current GLIBC version.*
```
ldd --version
```
*These two commands will find out the current GLIBCXX versions. The first command returns a path you must use for the second command, which I have higlighted in white. It may be different for you.*

![image](https://user-images.githubusercontent.com/44985633/146113701-750d0bf3-23c0-412c-811e-67527046293c.png)

Based on the error you provided, you will need GLIBC with a version of 2.29 or higher, and GLIBCXX with a version of 3.4.26 or higher. If both `libc6` and `libstdc++6` are at their latest versions, your version of Debian may be too old to run Saturn ME.

**Comment by integerbang** [comment]
@PaperVb64, I've researched how you're supposed to upgrade to a more recent release of Debian (so you'd be able to update your dependencies) and this is what I've managed to find so far.

Try updating Linux on Chrome OS using the first and second instructions provided by the "Fix problems with Linux" section in [this Chromebook Help page](https://support.google.com/chromebook/answer/9145439). Afterwards, go to `chrome://flags` on a Chrome window then look for a flag named "Debian version for new Crostini containers." Once you have found that, change the option for the flag to "Bullseye." As soon you have done that, reset Linux on Chrome OS using the instructions from both the "Turn off Linux" and "Turn on Linux" sections in the same Chromebook Help page mentioned prior.

I haven't used Chrome OS before so I can't verify that these instructions will solve your issue. Hope this helps, regardless!

**Comment by PaperVb64** [comment]
> Can you try running these two commands for me, and sending back the entire output?
> 
> _This command will find out the current GLIBC version._
> 
> ```
> ldd --version
> ```
> 
> _These two commands will find out the current GLIBCXX versions. The first command returns a path you must use for the second command, which I have higlighted in white. It may be different for you._
> 
> ![image](https://user-images.githubusercontent.com/44985633/146113701-750d0bf3-23c0-412c-811e-67527046293c.png)
> 
> Based on the error you provided, you will need GLIBC with a version of 2.29 or higher, and GLIBCXX with a version of 3.4.26 or higher. If both `libc6` and `libstdc++6` are at their latest versions, your version of Debian may be too old to run Saturn ME.

Holy Crap! It's 1 version behind!

**Comment by PaperVb64** [comment]
> @PaperVb64, I've researched how you're supposed to switch to a more recent release of Debian (so you'd be able to use newer versions of Saturn: Moon Edition's dependencies) on Crostini (a.k.a. Linux on Chrome OS) and this is what I've managed to find so far.
> 
> Try updating Crostini using the first and second instructions provided by the "Fix problems with Linux" section in [this Chromebook Help page](https://support.google.com/chromebook/answer/9145439). Afterwards, go to `chrome://flags` on a Chrome window then look for a flag named "Debian version for new Crostini containers." Once you have found that, change the option for the flag to "Bullseye." As soon you have done that, replace your container using the instructions from both the "Turn off Linux" and "Turn on Linux" sections in the same Chromebook Help page that was mentioned prior.
> 
> I haven't used Chrome OS before so I can't verify that these instructions will definitively solve your issue. Hope this helps, regardless!

if NO ONE remembers, i was on an School chromebook the last time, and i still am. Well, i'm not. Well... It's complicated! It's MY chromebook, but i'm using my SCHOOL account, so it's locked away form linux, and i cheated my way to linux by searching up the terminal, and bringing up the install prompt through THERE. So is there any other version?

**Comment by integerbang** [comment]
> if NO ONE remembers, i was on an School chromebook the last time, and i still am. Well, i'm not. Well... It's complicated! It's MY chromebook, but i'm using my SCHOOL account, so it's locked away form linux, and i cheated my way to linux by searching up the terminal, and bringing up the install prompt through THERE. So is there any other way to upgrade?

Okay. Firstly, calm down. I'm only trying my best to assist you and simply responding by harshly pointing out how you got Crostini on the device isn't really helping anyone. I apologize that I did not recall what you've brought up in your previous issue, but there was no reason to lash out like that towards someone trying to help.

Secondly, my only suggestion is to follow [the standard prodecure for upgrading a Debian system provided by the Debian team themselves](https://www.debian.org/releases/stable/amd64/release-notes/ch-upgrading.en.html). Either that or you should migrate to a regular Google account for your Chromebook whenever you can (especially since you shouldn't be using your organization-provided account for anything unrelated to its intended use).

Hope this helps.

**Comment by PaperVb64** [comment]
> > if NO ONE remembers, i was on an School chromebook the last time, and i still am. Well, i'm not. Well... It's complicated! It's MY chromebook, but i'm using my SCHOOL account, so it's locked away form linux, and i cheated my way to linux by searching up the terminal, and bringing up the install prompt through THERE. So is there any other way to upgrade?
> 
> Okay. Firstly, calm down. I'm only trying my best to assist you and simply responding by harshly pointing out how you got Crostini on the device isn't really helping anyone. I apologize that I did not recall what you've brought up in your previous issue, but there was no reason to lash out towards someone trying to help out just for something as simple as that.
> 
> Secondly, my only suggestion is to follow [the standard prodecure for upgrading a Debian 10 system provided by the developers themselves](https://www.debian.org/releases/stable/amd64/release-notes/ch-upgrading.en.html). Either that or you should migrate to a regular Google account for your Chromebook whenever you can (especially since you shouldn't be using your organization-provided account for anything unrelated to its intended use).
> 
> Hope this helps.

First off, sorry about how i responded. I wasn't trying to come off as lashing out. And second, the official guide is too hard for a noob like me. Everything i do is based off of tutorials.

**Comment by integerbang** [comment]
> First off, sorry about how i responded. I wasn't trying to come off as lashing out. And second, the official guide is too hard for a noob like me. Everything i do is based off of tutorials. 

There isn't much I can really do considering what your current situation. As I already mentioned, you should consider [adding your regular Google account](https://www.google.com/chromebook/howto/add-another-account/) or create one instead of trying to use an account that was provided by your school.

**Comment by PaperVb64** [comment]
guess chromebooks suck grass
