### ISSUE TITLE
Character Select / Easier UI / UI Guides

### ISSUE THREAD

**Issue by PaperVb64** [Llennpie/Saturn#6]
I want to use one character sometimes, and sometimes cause of all the mods, that on character isn't playable. So can you PLEEEASE add a Character Select. Also, the machinima interface is WAAAY too hard to navigate in moon, so could you change that too please? And also, I don't know how to swap texture mods and stuff, so could you add some menu for that?
(P.S: I would say only to add this stuff to moon edition, but i don't want it to be unfair to people that prefer what they already have).

**Comment by integerbang** [comment]
> yeah, can you?

Yes, you can. Open another issue with whatever you want to suggest and it should be given the `enhancement` label soon afterward.

**Comment by PaperVb64** [comment]
ok cool i'mma just change this rq

**Comment by PaperVb64** [comment]
oh! thanks!

**Comment by PaperVb64** [comment]
Also, quick ask. I have Saturn Moon on my windows computer (cause i type and do stuff on chromebook lol), And i saw the new version on Moon. Do i have to install a completely new version, or does the program automatically update?

**Comment by Llennpie** [comment]
> Do i have to install a completely new version, or does the program automatically update?

You have to install the latest build from the [releases](github.com/Llennpie/Saturn/releases/latest) page. An auto-updater is not planned at the moment, although I may add an update notifier at some point.

**Comment by PaperVb64** [comment]
oh! Cool!

**Comment by PaperVb64** [comment]
Also, AYYYYYYYY i got it running on chromebook!

**Comment by PaperVb64** [comment]
only moon seems to work tho, cause i tried installing the vanilla version, and i couldn't use the make command. I think it wasn't added, or the installation process skipped over it.

**Comment by PaperVb64** [comment]
also, is there support for adding custom levels?

**Comment by PaperVb64** [comment]
and can you even do multiplayer

**Comment by Llennpie** [comment]
I'd say this has all been implemented now with Legacy's CC-able model and CometSPARK support. A documentation is coming soon with info on how to replace/edit textures for Mario and custom models.
